export enum TaskLogActions {
  CREATE = 'CREATE',
  DELETE = 'DELETE',
  RENAME = 'RENAME',
  UPD_PRIORITY = 'UPD_PRIORITY',
  UPD_DESCRIPTION = 'UPD_DESCRIPTION',
  UPD_DUE_DATE = 'UPD_DUE_DATE',
  MOVE = 'MOVE',
}
