version: "3"

services:
   frontend:
      build: .
      container_name: rdncy-react-app-2-frontend
      ports:
         - "5000:5000"
      volumes:
         - /app/node_modules
         - .:/app
      restart: always
