version: '3'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      NODE_ENV: dev
      PORT: '3000'
      DB_HOST: tebesski-react-app-2-db
      DB_PORT: '5432'
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_DATABASE: tebesski-react-app-2-db
      SYNCHRONIZE: 'true'
    restart: always
    depends_on:
      tebesski-react-app-2-db:
        condition: service_healthy

  tebesski-react-app-2-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tebesski-react-app-2-db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    restart: always
